import './globals.css'
import Footer from "@/components/footer/Footer"
import Navbar from "@/components/navbar/Navbar"

export const metadata = {
  title: 'Boilerservice',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <body className="min-h-screen flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
